language: node_js
deploy:
  api_key:
    secure: K9Az5pNpX/82v1ZsAOUj6ytOtirDy7cAYZS/g0OgzqO7+W/yuXVSbeUdD3/g2k9JjAJMzgOak8V7pV4KnsblBUzus1B8h0uIiHxrw4odtMGo+tP/D3eS9ggy7j/efNeEsl/xvgTrOg1MXtBRYNRhzxwh6KFtDM7JGWUXl7YlDnZ/bAdx8HL/5DceyNXBGUoMPKLueFTkLAHZsNgaFm3mWCnIKKHPkI1kqbubMygNvjAyQ0DgQTnr3JEwPTnmi2iFpek9NZmXbm0V5paMp4QHaG96E+g0RdF/c97Hvh37AslP+l00xkei1QpxFektRM1u0RkE036HUYU7HpsH1inLWoxdyalwvHdhBQnCaoqYA1y7Iy5TRTNKt4JgHF5V95J/HXgOEMAkzOnm2nRanER+LE0Ic2KZGpvxoMWUhNs5Lty7VtBGb7FextMhE+vskxp2AqzAs0/fGb5mKcj5M0lEOL5DR+JcZ13W4+e3H63zIM5qqD++RmdBcEN7cz47rnh7NRXwXNYixjL2cn/iBGueyM7JFr9nIaN0qrpyEM8jOz5neBiFbe3X5dU99AhjC3qk2mJEA0bPsjxqqkOIfYJuklseJUjE1Ztg4xfJMibAjYEPsdkp965bmWrlUsRwDaAIB0W3zf6JJJfIZZWEKg+Us0jY5gN6MpQGfFCDXMPmNDY=
api_key: 
email: laki944@gmail.com
provider: npm
